image: registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
before_script:
  - docker login -u $CI_REGISTRY_USER -p 5orfYHapCfCK4SMvxYdL $CI_REGISTRY


Build:
   
  stage: build
  
  services:
    - registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
  
   
  script:
    - rm -f src/shared/config.js
   

    - cat > src/shared/config.js <<-EOF
        export const config = {
        API_URL : 'http://77.196.241.97:8080/pactng-backend/api/v1/',
        API_AUTH : 'http://77.196.241.97:8080/pactng-backend/api/auth/',
        API_MANAGE : 'http://77.196.241.97:8080/pactng-backend/management/',
      }
      EOF

    - docker build --no-cache -t registry.cdadt.fr/pacng/front .
    - docker push registry.cdadt.fr/pacng/front
