image: registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
before_script:
  - docker login -u $CI_REGISTRY_USER -p 5orfYHapCfCK4SMvxYdL $CI_REGISTRY


Build:
   
  stage: build
  
  services:
    - registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
  
   
  script:

    - sed '2,4d' src/shared/config.js
    - sed -i 's@^//API_URL@API_URL@' src/shared/config.js
    - sed -i 's@^//API_AUTH@API_AUTH@' src/shared/config.js
    - sed -i 's@^//API_MANAGE@API_MANAGE@' src/shared/config.js
    - docker build --no-cache -t registry.cdadt.fr/pacng/front .
    - docker push registry.cdadt.fr/pacng/front
