image: registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
before_script:
  - docker login -u $CI_REGISTRY_USER -p 5orfYHapCfCK4SMvxYdL $CI_REGISTRY


build site:
  image: node:12-alpine
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:6
  stage: test
  script:
    - npm install --progress=false
    - npm run unit


Build image:
   
  stage: build
  
  services:
    - registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
  
   
  script:

    - sed '2,4d' src/shared/config.js
    - sed -i "s@^//@ @g" src/shared/config.js
    - docker build --no-cache -t registry.cdadt.fr/pacng/front .
    - docker push registry.cdadt.fr/pacng/front
