image: registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
before_script:
  - docker login -u $CI_REGISTRY_USER -p 5orfYHapCfCK4SMvxYdL $CI_REGISTRY


Build:
   
  stage: build
  
  services:
    - registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
  
   
  script:
    - sed '2d;5d' src/shared/config.js
    - sed -i 's@//API_URL@API_URL@g'
    - sed -i 's@//API_AUTH@API_AUTH@g'
    - sed -i '$@//API_MANAGE@API_MANAGE@g'
    - docker build --no-cache -t registry.cdadt.fr/pacng/front .
    - docker push registry.cdadt.fr/pacng/front
