image: registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
before_script:
  - docker login -u $CI_REGISTRY_USER -p 5orfYHapCfCK4SMvxYdL $CI_REGISTRY


Build:
   
  stage: build
  
  services:
    - registry.cdadt.fr/appui-specialise/conteneurisation/conteneur/docker-gitlab-ci:latest
  
   
  script:

    - sed '2,4d' src/shared/config.js
    - sed -i "s@^//API_URL : 'http://77.196.241.97:8080/pactng-backend/api/v1/'@API_URL : 'http://77.196.241.97:8080/pactng-backend/api/v1/'@" src/shared/config.js
    - sed -i "s@^//API_AUTH : 'http://77.196.241.97:8080/pactng-backend/api/auth/'@API_AUTH : \'http://77.196.241.97:8080/pactng-backend/api/auth/'@" src/shared/config.js
    - sed -i "s@^//API_MANAGE : 'http://77.196.241.97:8080/pactng-backend/management/'@//API_MANAGE : 'http://77.196.241.97:8080/pactng-backend/management/'@" src/shared/config.js
    - docker build --no-cache -t registry.cdadt.fr/pacng/front .
    - docker push registry.cdadt.fr/pacng/front
